#!/bin/sh
set -e

# Bundler
bundle install

# Heroku configuration
if ! git remote | grep heroku >/dev/null; then
  git remote add heroku git@heroku.com:pathway-homes.git
fi

# Create all the databases
bin/rake db:create:all

# Seed
bin/rake dev:seed
