#!/bin/sh
set -e

if ! which psql >/dev/null 2>&1; then
  echo "PostgreSQL is required. Please use Homebrew or <http://postgresapp.com/>."
  exit 1
fi

# Bundler
bundle install

# Heroku configuration
if ! git remote | grep heroku >/dev/null; then
  git remote add heroku git@heroku.com:pathway-homes.git
fi

# Create all the databases
bin/rake db:create:all

# Seed
bin/rake dev:seed
